Repository HYF-Class19/workflow-group-3, pull requests merged in 2022-07, with the labels that each got.

#7 Galal-bio.md
  .cspell.json
  .gitignore
  images/galal.png
  images/galal2.png
  images/galal3.png
  images/galal4.png
  images/img
  package-lock.json
  package.json
  students-bio/galal.md
Labels: md, individual

#11 created a folder inna-bio.md and added some info
  .cspell.json
  students-bio/inna-bio.md
Labels: md, individual

#13 Added new azima-bio.md file with images
  images/azi-bio-ph..jpg
  images/keep calm.png
  students-bio/azima-bio.md
Labels: md, individual

#12 Readme-group-3
  .cspell.json
  .vscode/settings.json
  README.md
  images/azima.png
  images/gopi.png
  images/inna.png
  images/john.png
  images/logo.png
  images/rengani.png
Labels: question, group, md

#15 Group README
  README.md
Labels: group, md

#16 add team table contributin
  README.md
Labels: group, md

#17 JohnOlutubo: Create My bio with md
  .cspell.json
  images/john-img.jpg
  images/john_startup.png
  students-bio/john.md
Labels: md

#18 Gopiben-bio
  .cspell.json
  students-bio/gopi.md
Labels: deliverable, md, individual

#19 add table photo and flag
  students-bio/gopi.md
Labels: deliverable, md, individual
